### PR TITLE
Add end-to-end spec test

### PR DESCRIPTION
**Pull request by mihael**
1. Adds simple end to end test.

Simulates a random fail. Checks if the issue gets reported to this repository via a comment (https://github.com/tansaku/report_intermittent_fails/issues/3). The comment gets deleted afterwards.

2. Plus some refactor and small improvements and ideas.

### CODE REVIEW

**Comment by tansaku** [comment]
@mihael this looks really great!  I saw the opened issue - really great to see.

Running locally I notice we are now missing coverage in a few places:

```
+----------+------------------------------------------------------+-------+--------+-----------------------------------------+
| coverage | file                                                 | lines | missed | missing                                 |
+----------+------------------------------------------------------+-------+--------+-----------------------------------------+
|  57.14%  | lib/report_intermittent_fails/github.rb              | 28    | 12     | 41, 43-45, 47, 49-50, 52-53, 55, 61, 63 |
|  76.92%  | lib/report_intermittent_fails/ci_helper.rb           | 13    | 3      | 35-36, 38                               |
|  91.18%  | lib/report_intermittent_fails/rerun_failing_tests.rb | 68    | 6      | 24, 35-36, 106, 108, 110                |
|  96.55%  | lib/report_intermittent_fails/config.rb              | 29    | 1      | 38                                      |
+----------+------------------------------------------------------+-------+--------+-----------------------------------------+
```

Do you think it is worth making sure those places are covered before merging?

**Comment by tansaku** [comment]
I also got a few rubocop offenses when running `bundle exec rake` locally:

```
Offenses:

lib/report_intermittent_fails/config.rb:46:7: C: [Corrected] Style/StringLiterals: Prefer single-quoted strings when you don't need string interpolation or special symbols.
      "Intermittent fail: "
      ^^^^^^^^^^^^^^^^^^^^^
lib/report_intermittent_fails/github.rb:35:5: C: Metrics/AbcSize: Assignment Branch Condition size for issue_was_commented_recently? is too high. [<6, 16, 5> 17.8/15]
    def self.issue_was_commented_recently?(title, ...
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
lib/report_intermittent_fails/github.rb:35:5: C: Metrics/MethodLength: Method has too many lines. [12/10]
    def self.issue_was_commented_recently?(title, ...
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
lib/report_intermittent_fails/github.rb:35:43: C: Metrics/ParameterLists: Avoid parameter lists longer than 5 parameters. [6/5]
    def self.issue_was_commented_recently?(title, ...
                                          ^^^^^^^
lib/report_intermittent_fails/github.rb:51:9: C: [Corrected] Layout/LeadingCommentSpace: Missing space after #.
        #delete the comment before returning
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
lib/report_intermittent_fails/rerun_failing_tests.rb:59:3: C: Metrics/AbcSize: Assignment Branch Condition size for check_for_and_submit_fails is too high. [<2, 15, 0> 15.13/15]
  def self.check_for_and_submit_fails(failed_first_run_specs, ...
  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
spec/endtoend_spec.rb:28:121: C: Layout/LineLength: Line is too long. [123/120]
          expect(ReportIntermittentFails::Github.issue_was_commented_recently?(title, minutes: 1, delete: true)).to eq true
```
Maybe worth checking these out?

Would be great to have our CI automatically flagging coverage and rubocop issues, or some pre-commit hook or something maybe ...?

**Comment by mihael** [comment]
@tansaku thank's for taking a look, agree 💯and will action your suggestions...

as an MVP this branch can be verified against an app, can you do that maybe, you already have the setup, right? 🙏

**Comment by tansaku** [comment]
I can certainly try - although I haven't had much luck getting actual intermittent fails on that app yet :-)

**Comment by tansaku** [comment]
updating app to use that branch:

```
gem 'report_intermittent_fails', git: 'https://github.com/tansaku/report_intermittent_fails', branch: 'randomfail-endtoend'
```

**Comment by mihael** [comment]
@tansaku you could try adding this random-failing-spec example to the other repo, this would give you a **_reliable_** random fail :)
```
RSpec.describe 'End to end' do
     let(:intermittent_fail_indicator_file) { './tmp/failed_on_first_run.txt' }
     before do
       Dir.mkdir('tmp') unless File.exist?('tmp')
     end

     context 'randomly failing' do
       it 'succeeds when rerun' do
         if File.exist?(intermittent_fail_indicator_file)
           # this is the second run
           # when the file exists, it means the first run has happened,
           File.delete(intermittent_fail_indicator_file)
         else
           # this is the first run, no indicator files present
           # so generate the indicator file and fail,
           # this simulates a random fail, the subsequent run would then succeed
           File.write(intermittent_fail_indicator_file, 'Fail')
           expect('random').to eq 'fail'
         end
       end
     end
end

```

**Review by tansaku — APPROVED** [review]
totally awesome!

**Pull request merged**
